
actions_path 'actions/'
fastlane_version "2.68.0"

default_platform :android

before_all do
    # ensure_git_branch
    # ensure_git_status_clean
    # git_pull
end

platform :android do
    before_all do
        gradle(
            task: 'clean',
            project_dir: 'android/'
        )
        increment_android_version_code(path: './android/app/build.gradle')
    end

    lane :beta do
        increment_android_version_name(
            path: './android/app/build.gradle',
            type: "patch"
        )

        gradle(
            task: 'assemble',
            build_type: 'Debug',
            project_dir: 'android/'
        )


        # don't mind publishing to GitHub since it is a dummy organization
        crashlytics(
          api_token: "afe07034e00f5c1cb31684b4d7aeafbd81def414",
          build_secret: "0292321e17f88dd00d174718a02608f6675a17f51cf81399b88012f037b6c77f",
        )

        git_commit(
            path: File.dirname('./android/app/build.gradle'),
            message: "bump version"
        )

        add_git_tag(
            tag: "v#{lane_context[SharedValues::ANDROID_VERSION_NAME]}"
        )

        push_to_git_remote
    end
end